import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const colorSchematics = {
    cardBgColor:"#FFEDEB",
    cardColor:"#fdd3d1",
    primaryColor:"#FF888",
    secondaryColor:"",
    widgetBgColor:"#fce5e2",
    fontColor:"#410007",
    buttonBgColor:"#FFDAD8",
    buttonHoverColor:"#ffc8c6",
    footerFontColor:"",
    cardHoverColor:"#FFB3B1"
  }
  return (
    <html lang="en">
      <body className={inter.className}>
         <Navbar  colorVarient={colorSchematics}/>
        {children}
         <Footer/>
        </body>
    </html>
  )
}
